# @package _global_

defaults:
  - override /data: navsim
  - override /model: fastwam_navsim_dit
  - _self_

# Global batch = batch_size * expected_world_size * gradient_accumulation_steps
#              = 3 * 16 * 4 = 192.
batch_size: 3
num_workers: 2
expected_world_size: 16

model:
  mot_checkpoint_mixed_attn: false

data:
  train:
    video_size: [192, 352]
    camera_layout: front
    missing_sensor_policy: ${oc.env:NAVSIM_MISSING_SENSOR_POLICY,skip}
    generate_flow_gt: false
    generate_flow_rgb: true
    flow_bev_size: [200, 200]
    flow_resolution: 0.5
    flow_x_range: [0.0, 100.0]
    flow_y_range: [-50.0, 50.0]
    flow_horizon_index: 0
    flow_include_agents: true
    flow_cache_dir: ${oc.env:NAVSIM_FLOW_CACHE_DIR,/mnt/zhaozc_workspace/data/fastwam_xty_dit_flow_dataset_motus_rigid}
    flow_rgb_cache_dir: ${oc.env:NAVSIM_FLOW_RGB_CACHE_DIR,/mnt/zhaozc_workspace/data/fastwam_xty_dpflow_rgb_dataset_official_192x352}
    flow_rgb_ckpt: sintel
    flow_rgb_frame_a: 0
    flow_rgb_frame_b: 1

lr_scheduler_type: "cosine"
learning_rate: 1e-4
num_epochs: 100
max_steps: 44000
log_every: 10
save_every: 0
save_steps: [3000, 11000, 22000, 33000, 44000]
eval_every: 3000

gradient_accumulation_steps: 4
mixed_precision: "bf16"
max_grad_norm: 1.0
weight_decay: 1e-2
resume: null
